---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Configures infrastructure for bitwarden_rs

#Metadata:
#  template metadata

Parameters:
  Application:
    Type: String
    Description: Application name e.g. bwrs.
  Environment:
    Type: String
    Description: Environment name e.g. prod, dev.

#Rules:
#  set of rules

#Mappings:
#  set of mappings

#Conditions:
#  set of conditions

#Transform:
#  set of transforms

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName:
        !Join
          - '-'
          - - !Ref Application
            - !Ref Environment
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1

#Outputs:
#  set of outputs
